import Head from "next/head";
import Image from "next/image";
import { Montserrat } from "@next/font/google";
import Logo from "/public/logo.svg";
import CardsList from "@/components/CardsList";
import { SearchForm } from "@/components/SearchForm";

const montSerrat = Montserrat({ weight: ["500", "600"], subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Windbnb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" min-h-screen pb-10 mx-auto flex flex-col">
        <SearchForm />
        <div className="container mx-auto">
          <CardsList />
        </div>
      </main>
    </>
  );
}
