import Head from "next/head";
import { Montserrat } from "@next/font/google";
import { Logo } from "@/components/Logo";
import CardsList from "@/components/CardsList";
import { SearchForm } from "@/components/SearchForm";
import data from "@/data.json";
import { useState } from "react";
import { SearchBar } from "@/components/SearchBar";
import { filterLocations } from "@/utils/filterLocations";

const montSerrat = Montserrat({ weight: ["500", "600"], subsets: ["latin"] });

export default function Home() {
  const [filter, setFilter] = useState({});
  const [toggleSearch, setToggleSearch] = useState(false);
  const { location, guests } = filter;
  const filteredLocations = filterLocations(location, guests);

  return (
    <>
      <Head>
        <title>Windbnb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/triangleLogo.png" />
      </Head>
      <div className="min-h-screen">
        {toggleSearch && (
          <SearchForm
            setFilter={setFilter}
            setToggleSearch={setToggleSearch}
            data={data}
          />
        )}

        <div
          className={`${
            toggleSearch && "bg-[#4F4F4F66] min-h-screen  brightness-50 z-50 "
          }`}
        >
          <div
            className={`mx-auto max-w-7xl ${montSerrat.className} pb-36 min-h-screen`}
          >
            <header className="flex flex-col gap-10 pt-[22px] sm:flex-row sm:justify-between sm:items-center sm:pt-8 container mx-auto px-3 min-[1440px]:px-0">
              <Logo />

              <SearchBar filter={filter} setToggleSearch={setToggleSearch} />
            </header>

            {filteredLocations ? (
              <CardsList data={filteredLocations} />
            ) : (
              <CardsList data={data} />
            )}
          </div>

          <footer className="flex justify-center pb-7">
            <p className="text-[#828282] font-medium text-sm">
              created by{" "}
              <a
                href="https://devchallenges.io/portfolio/leoron95"
                className="font-bold underline"
              >
                leoron95
              </a>{" "}
              - <a href="https://devchallenges.io/"> devChallenges.io</a>
            </p>
          </footer>
        </div>
      </div>
    </>
  );
}
